clear;
close all;
rng(1); %control the randomness
img_as_rows=zeros(19200,16);%storing 16 images as vectors
nth_image_avg=zeros(19200,1);
mean_matrix=zeros(19200,1);
final_matrix=imread("../data/data_fruit/image_1.png");
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,1)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_2.png');
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,2)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_3.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,3)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_4.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,4)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_5.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,5)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_6.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,6)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_7.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,7)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_8.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,8)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_9.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,9)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_10.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,10)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_11.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,11)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_12.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,12)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_13.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,13)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_14.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,14)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_15.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,15)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
final_matrix=imread('../data/data_fruit/image_16.png')
final_matrix=reshape(final_matrix,19200,1);
nth_image_avg=double(final_matrix);
img_as_rows(:,16)=nth_image_avg;
mean_matrix=mean_matrix+nth_image_avg;
mean_matrix=mean_matrix/16;%getting the mean matrix dividing by total number of images
cov_helper=bsxfun(@minus,img_as_rows,mean_matrix);
cov_matrix=cov_helper*cov_helper.'; %found a good cheeky way to calculate covariance without using cov
[R,C]=eigs(cov_matrix,10);
value_1=R(:,1);
value_2=R(:,2);
value_3=R(:,3);
value_4=R(:,4);
sample_1=image(rescale(reshape(mean_matrix,80,80,3)));
sample_2=image(rescale(reshape(value_1,80,80,3)));
sample_3=image(rescale(reshape(value_2,80,80,3)));
sample_4=image(rescale(reshape(value_3,80,80,3)));
sample_5=image(rescale(reshape(value_4,80,80,3)));
subplot(2,3,1),image(rescale(reshape(mean_matrix,80,80,3)));
subplot(2,3,2),image(rescale(reshape(value_1,80,80,3)));
subplot(2,3,3),image(rescale(reshape(value_2,80,80,3)));
subplot(2,3,4),image(rescale(reshape(value_3,80,80,3)));
subplot(2,3,5),image(rescale(reshape(value_4,80,80,3)));
eigenvalue_10=zeros(10,1);
for i=1:10
    eigenvalue_10(i)=C(i,i);
end
figure(2);
plot(eigenvalue_10);
closest_image=zeros(19200,16); 
mean_1=dot(mean_matrix,value_1);
mean_2=dot(mean_matrix,value_2);
mean_3=dot(mean_matrix,value_3);
mean_4=dot(mean_matrix,value_4);
var_1=dot(img_as_rows(:,1),value_1);
var_2=dot(img_as_rows(:,1),value_2);
var_3=dot(img_as_rows(:,1),value_3);
var_4=dot(img_as_rows(:,1),value_4);
coef=(dot(img_as_rows(:,1),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,1)=img_column;
var_1=dot(img_as_rows(:,2),value_1);
var_2=dot(img_as_rows(:,2),value_2);
var_3=dot(img_as_rows(:,2),value_3);
var_4=dot(img_as_rows(:,2),value_4);
coef=(dot(img_as_rows(:,2),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,2)=img_column;
var_1=dot(img_as_rows(:,3),value_1);
var_2=dot(img_as_rows(:,3),value_2);
var_3=dot(img_as_rows(:,3),value_3);
var_4=dot(img_as_rows(:,3),value_4);
coef=(dot(img_as_rows(:,3),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,3)=img_column;
var_1=dot(img_as_rows(:,4),value_1);
var_2=dot(img_as_rows(:,4),value_2);
var_3=dot(img_as_rows(:,4),value_3);
var_4=dot(img_as_rows(:,4),value_4);
coef=(dot(img_as_rows(:,4),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,4)=img_column;
var_1=dot(img_as_rows(:,5),value_1);
var_2=dot(img_as_rows(:,5),value_2);
var_3=dot(img_as_rows(:,5),value_3);
var_4=dot(img_as_rows(:,5),value_4);
coef=(dot(img_as_rows(:,5),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,5)=img_column;
var_1=dot(img_as_rows(:,6),value_1);
var_2=dot(img_as_rows(:,6),value_2);
var_3=dot(img_as_rows(:,6),value_3);
var_4=dot(img_as_rows(:,6),value_4);
coef=(dot(img_as_rows(:,6),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,6)=img_column;
var_1=dot(img_as_rows(:,7),value_1);
var_2=dot(img_as_rows(:,7),value_2);
var_3=dot(img_as_rows(:,7),value_3);
var_4=dot(img_as_rows(:,7),value_4);
coef=(dot(img_as_rows(:,7),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,7)=img_column;
var_1=dot(img_as_rows(:,8),value_1);
var_2=dot(img_as_rows(:,8),value_2);
var_3=dot(img_as_rows(:,8),value_3);
var_4=dot(img_as_rows(:,8),value_4);
coef=(dot(img_as_rows(:,8),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,8)=img_column;
var_1=dot(img_as_rows(:,9),value_1);
var_2=dot(img_as_rows(:,9),value_2);
var_3=dot(img_as_rows(:,9),value_3);
var_4=dot(img_as_rows(:,9),value_4);
coef=(dot(img_as_rows(:,9),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,9)=img_column;
var_1=dot(img_as_rows(:,10),value_1);
var_2=dot(img_as_rows(:,10),value_2);
var_3=dot(img_as_rows(:,10),value_3);
var_4=dot(img_as_rows(:,10),value_4);
coef=(dot(img_as_rows(:,10),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,10)=img_column;
var_1=dot(img_as_rows(:,11),value_1);
var_2=dot(img_as_rows(:,11),value_2);
var_3=dot(img_as_rows(:,11),value_3);
var_4=dot(img_as_rows(:,11),value_4);
coef=(dot(img_as_rows(:,11),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,11)=img_column;
var_1=dot(img_as_rows(:,12),value_1);
var_2=dot(img_as_rows(:,12),value_2);
var_3=dot(img_as_rows(:,12),value_3);
var_4=dot(img_as_rows(:,12),value_4);
coef=(dot(img_as_rows(:,12),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,12)=img_column;
var_1=dot(img_as_rows(:,13),value_1);
var_2=dot(img_as_rows(:,13),value_2);
var_3=dot(img_as_rows(:,13),value_3);
var_4=dot(img_as_rows(:,13),value_4);
coef=(dot(img_as_rows(:,13),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,13)=img_column;
var_1=dot(img_as_rows(:,14),value_1);
var_2=dot(img_as_rows(:,14),value_2);
var_3=dot(img_as_rows(:,14),value_3);
var_4=dot(img_as_rows(:,14),value_4);
coef=(dot(img_as_rows(:,14),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,14)=img_column;
var_1=dot(img_as_rows(:,15),value_1);
var_2=dot(img_as_rows(:,15),value_2);
var_3=dot(img_as_rows(:,15),value_3);
var_4=dot(img_as_rows(:,15),value_4);
coef=(dot(img_as_rows(:,15),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,15)=img_column;
var_1=dot(img_as_rows(:,16),value_1);
var_2=dot(img_as_rows(:,16),value_2);
var_3=dot(img_as_rows(:,16),value_3);
var_4=dot(img_as_rows(:,16),value_4);
coef=(dot(img_as_rows(:,16),mean_matrix)-var_1*mean_1-var_2*mean_2-var_3*mean_3-var_4*mean_4)/(dot(mean_matrix,mean_matrix)-mean_1*mean_1-mean_2*mean_2-mean_3*mean_3-mean_4*mean_4);
img_column=coef*mean_matrix+(var_2-mean_2*coef)*value_2+(var_1-mean_1*coef)*value_1+(var_3-mean_3*coef)*value_3+(var_4-mean_4*coef)*value_4;
closest_image(:,16)=img_column;
figure(3);
sample_closest=rescale(reshape(closest_image(:,1),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,1),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(4);
sample_closest=rescale(reshape(closest_image(:,2),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,2),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(5);
sample_closest=rescale(reshape(closest_image(:,3),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,3),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(6);
sample_closest=rescale(reshape(closest_image(:,4),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,4),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(7);
sample_closest=rescale(reshape(closest_image(:,5),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,5),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(8);
sample_closest=rescale(reshape(closest_image(:,6),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,6),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(9);
sample_closest=rescale(reshape(closest_image(:,7),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,7),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(10);
sample_closest=rescale(reshape(closest_image(:,8),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,8),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(11);
sample_closest=rescale(reshape(closest_image(:,9),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,9),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(12);
sample_closest=rescale(reshape(closest_image(:,10),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,10),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(13);
sample_closest=rescale(reshape(closest_image(:,11),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,11),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(14);
sample_closest=rescale(reshape(closest_image(:,12),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,12),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(15);
sample_closest=rescale(reshape(closest_image(:,13),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,13),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(16);
sample_closest=rescale(reshape(closest_image(:,14),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,14),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(17);
sample_closest=rescale(reshape(closest_image(:,15),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,15),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(18);
sample_closest=rescale(reshape(closest_image(:,16),80,80,3));
sample_original=rescale(reshape(img_as_rows(:,16),80,80,3));
subplot(1,2,2),image(sample_closest);
subplot(1,2,1),image(sample_original);
figure(19);
V=C(1:4,1:4);
D=R(:,1:4);
mani=V^0.5;
final_m= D*mani*D.';
for i=1:3
    new_matrix=randn(19200,1);
    image_store=mean_matrix+final_m*new_matrix; 
    final_image=rescale(reshape(image_store,80,80,3)); 
    subplot(3,3,i),image(final_image);
end












